In [1]:
# Load packages
library(mgcv)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(gridExtra)
library(grid)
library(writexl)
library(magrittr)
library(rstatix)
library(MASS)

Loading required package: nlme

This is mgcv 1.8-40. For overview type 'help("mgcv-package")'.

-- Attaching packages ------------------------------------------------------------------------------- tidyverse 1.3.1 --

v tibble  3.1.7     v dplyr   1.0.9
v tidyr   1.2.0     v stringr 1.4.0
v readr   2.1.2     v forcats 0.5.1
v purrr   0.3.4

-- Conflicts ---------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::collapse() masks nlme::collapse()
x dplyr::filter()   masks stats::filter()
x dplyr::lag()      masks stats::lag()


Attaching package: 'lubridate'


The following objects are masked from 'package:base':

    date, intersect, setdiff, union



Attaching package: 'gridExtra'


The following object is masked from 'package:dplyr':

    combine



Attaching package: 'magrittr'


The following object is masked from 'package:purrr':

    set_names


The following object is masked from 'package:tidyr':

    extract



Attaching package: 'rstatix'


The following object is masked from 'package:stats':

    filter



Attaching package: 'MASS'


The following object is masked from 'package:rstatix':

    select


The following object is masked from 'package:dplyr':

    select

In [79]:
PATH <- file.path("C:/Users/julia/OneDrive - London School of Hygiene and Tropical Medicine/Documents/LSHTM/Project") #"/home/andewegs/1_RSV_scripts/"
setwd(PATH)
getwd()
rsv.data <- read_csv(file = "Data/infection_status.csv")

[1] "C:/Users/julia/OneDrive - London School of Hygiene and Tropical Medicine/Documents/LSHTM/Project"

Rows: 682 Columns: 23
-- Column specification ------------------------------------------------------------------------------------------------
Delimiter: ","
dbl  (20): age_days, infection, IgG_PreF, IgA_PreF, IgG_PostF, IgA_PostF, Ig...
lgl   (1): IgA_Nn_household
date  (2): birthday, consultdate

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [80]:
spring <- c(3, 4, 5)
summer <- c(6, 7, 8)
autumn <- c (9, 10, 11)
winter <- c(1, 2, 12)

rsv.data <- rsv.data %>%
 mutate(
    Birth_mo = birthday %>% month()
  )%>%
    mutate(
        season_birth = case_when(
            Birth_mo %in% spring ~ "Spring",
            Birth_mo %in% summer ~ "Summer",
            Birth_mo %in% autumn ~ "Autumn",
            Birth_mo %in% winter ~ "Winter")
        )
head(rsv.data)

  age_days birthday   consultdate infection IgG_PreF  IgA_PreF IgG_PostF
1  676     2004-04-01 2006-02-06  1            0.3565  0.60       9.3264
2  600     2004-07-23 2006-03-15  1          772.3431 33.15     473.5323
3  588     2004-08-09 2006-03-20  0            0.1800  0.03       0.2100
4  591     2004-08-06 2006-03-20  1          740.2907 70.38     466.2055
5 1184     2002-12-29 2006-03-27  1         1999.2353    NA    1459.5921
6  686     2004-05-12 2006-03-29  1          807.2200    NA     838.7400
  IgA_PostF IgG_Ga    IgA_Ga <U+22EF>        household59 visitnursery_child
1  0.08      0.260000 0.01   <U+22EF> 0           0
2 14.52      3.130699 0.02   <U+22EF> 0           1
3  0.19      0.580000 0.03   <U+22EF> 0           0
4 49.78      1.886910 0.05   <U+22EF> 1           0
5    NA     55.896003   NA   <U+22EF> 1           0
6    NA     15.000000   NA   <U+22EF> 0           0
  visitnursery_house pregnancytime contacttotal contact04 contact59 sex
1 0                  NA             3            1        0         2
2 0                  NA            29           20        0         1
3 0                  NA             4            1        0         2
4 0                  NA             2            0        0         2
5 0                  NA             6            2        3         1
6 0                  NA             2            0        0         2
  Birth_mo season_birth
1  4       Spring
2  7       Summer
3  8       Summer
4  8       Summer
5 12       Winter
6  5       Spring

In [81]:
rsv.data$agegrp <- cut(rsv.data$age_days,
                    breaks=c(seq(0,730, by=30.25*2),
                             seq(909,2000, by=30.25*6)), 
                    include.lowest = T, right=F)

head(rsv.data)

  age_days birthday   consultdate infection IgG_PreF  IgA_PreF IgG_PostF
1  676     2004-04-01 2006-02-06  1            0.3565  0.60       9.3264
2  600     2004-07-23 2006-03-15  1          772.3431 33.15     473.5323
3  588     2004-08-09 2006-03-20  0            0.1800  0.03       0.2100
4  591     2004-08-06 2006-03-20  1          740.2907 70.38     466.2055
5 1184     2002-12-29 2006-03-27  1         1999.2353    NA    1459.5921
6  686     2004-05-12 2006-03-29  1          807.2200    NA     838.7400
  IgA_PostF IgG_Ga    IgA_Ga <U+22EF>        visitnursery_child visitnursery_house
1  0.08      0.260000 0.01   <U+22EF> 0                  0
2 14.52      3.130699 0.02   <U+22EF> 1                  0
3  0.19      0.580000 0.03   <U+22EF> 0                  0
4 49.78      1.886910 0.05   <U+22EF> 0                  0
5    NA     55.896003   NA   <U+22EF> 0                  0
6    NA     15.000000   NA   <U+22EF> 0                  0
  pregnancytime contacttotal contact04 contact59 sex Birth_mo season_birth
1 NA             3            1        0         2    4       Spring
2 NA            29           20        0         1    7       Summer
3 NA             4            1        0         2    8       Summer
4 NA             2            0        0         2    8       Summer
5 NA             6            2        3         1   12       Winter
6 NA             2            0        0         2    5       Spring
  agegrp
1 [666,726)
2 [544,605)
3 [544,605)
4 [544,605)
5 [1.09e+03,1.27e+03)
6 [666,726)

In [82]:
rsv.data <- subset (rsv.data, !is.na(visitnursery_child))
daycare <- subset(rsv.data, visitnursery_child == 1)
no_day <- subset(rsv.data, visitnursery_child == 0)

In [83]:
head(daycare)

  age_days birthday   consultdate infection IgG_PreF   IgA_PreF IgG_PostF
1  600     2004-07-23 2006-03-15  1          772.34314 33.15     473.5323
2 1282     2002-09-24 2006-03-29  1         2222.81750    NA    1500.0000
3  976     2003-08-01 2006-04-03  1            0.53000    NA       1.2300
4 1268     2002-10-13 2006-04-03  1         1357.84000    NA    5000.0000
5  957     2003-08-22 2006-04-05  1          561.33960    NA    1058.4328
6  567     2004-09-20 2006-04-10  1           22.06873  0.26     109.5198
  IgA_PostF IgG_Ga    IgA_Ga <U+22EF>        visitnursery_child visitnursery_house
1 14.52      3.130699 0.02   <U+22EF> 1                  0
2    NA     19.455700   NA   <U+22EF> 1                  0
3    NA      2.250200   NA   <U+22EF> 1                  0
4    NA      2.883200   NA   <U+22EF> 1                  0
5    NA     53.346847   NA   <U+22EF> 1                  0
6  1.07      2.590000 0.02   <U+22EF> 1                  0
  pregnancytime contacttotal contact04 contact59 sex Birth_mo season_birth
1 NA            29           20         0        1    7       Summer
2 NA            NA           NA        NA        2    9       Autumn
3 NA             4            0         0        2    8       Summer
4 NA            10            2         0        2   10       Autumn
5 NA             6            1         1        1    8       Summer
6 NA             5            3         0        1    9       Autumn
  agegrp
1 [544,605)
2 [1.27e+03,1.45e+03)
3 [909,1.09e+03)
4 [1.09e+03,1.27e+03)
5 [909,1.09e+03)
6 [544,605)

In [144]:
one <- subset(daycare, agegrp == "[1.82e+03,2e+03]")
two <- subset(no_day, agegrp == "[1.82e+03,2e+03]")

In [90]:
one

  age_days birthday   consultdate infection IgG_PreF  IgA_PreF IgG_PostF
1  82      2006-08-04 2006-10-25  0          29.27499 0.03      28.92621
2 102      2006-11-16 2007-02-26  1          73.48835 0.11     229.07401
3 107      2007-01-21 2007-05-08  0          62.60582 0.01      70.56261
4  81      2007-03-10 2007-05-30  0          88.51545 0.02     147.60778
5 104      2007-02-27 2007-06-11  0         197.44000 0.02     226.76000
6  96      2016-03-11 2016-06-15  0         113.03000 0.02      65.41000
7 110      2016-03-10 2016-06-28  0         129.79000 0.02      52.74000
8 100      2016-03-22 2016-06-30  0          59.11000 0.02      38.30000
9 114      2016-05-17 2016-09-08  0          52.30000 0.02      82.80000
  IgA_PostF IgG_Ga    IgA_Ga <U+22EF>        visitnursery_child visitnursery_house
1 0.28       0.830000 0.02   <U+22EF> 1                  0
2 0.90       3.599333 0.03   <U+22EF> 1                  1
3 0.01       2.680280 0.02   <U+22EF> 1                  0
4 0.02       0.802134 0.02   <U+22EF> 1                  1
5 0.03       0.920000 0.02   <U+22EF> 1                  0
6 0.02       1.410000 0.02   <U+22EF> 1                  1
7 0.02      18.210000 0.03   <U+22EF> 1                  0
8 0.02       0.710000 0.02   <U+22EF> 1                  1
9 0.02       0.620000 0.02   <U+22EF> 1                  0
  pregnancytime contacttotal contact04 contact59 sex Birth_mo season_birth
1 NA            NA           NA        NA        1    8       Summer
2 NA             3            1         0        1   11       Autumn
3 NA             3            0         0        1    1       Winter
4 NA            NA           NA        NA        1    3       Spring
5 NA            NA           NA        NA        1    2       Winter
6 39            17           10         0        2    3       Spring
7 NA             0           NA        NA        1    3       Spring
8 41             3            0         0        2    3       Spring
9 41            17           14         0        1    5       Spring
  agegrp
1 [60.5,121)
2 [60.5,121)
3 [60.5,121)
4 [60.5,121)
5 [60.5,121)
6 [60.5,121)
7 [60.5,121)
8 [60.5,121)
9 [60.5,121)

In [91]:
two

   age_days birthday   consultdate infection IgG_PreF  IgA_PreF IgG_PostF
1   66      2006-01-27 2006-04-03  0         117.49773 0.02      31.020256
2   70      2006-01-31 2006-04-11  0          83.92986 0.02      48.306774
3   97      2006-03-16 2006-06-21  1         117.75099 0.05      52.652352
4   85      2006-06-18 2006-09-11  0          70.03440 0.02      57.779319
5   85      2006-06-27 2006-09-20  0         116.75605 0.02      76.090000
6   68      2006-07-28 2006-10-04  0          87.06760 0.02      55.634513
7  108      2006-06-18 2006-10-04  0         165.23688 0.10      72.485884
8   67      2006-08-10 2006-10-16  0         291.37000 0.02     341.850000
9  120      2006-06-18 2006-10-16  0           1.02000 0.02       1.500000
10 112      2006-06-26 2006-10-16  0           4.46090 0.02       3.945000
11  97      2006-07-25 2006-10-30  1         282.51000 6.24     303.070000
12 103      2006-10-12 2007-01-23  0         292.70278 0.02     304.458637
13 111      2006-10-04 2007-01-23  0         128.15088 0.02      54.418908
14  86      2006-11-13 2007-02-07  0         114.08909 0.02      69.143757
15 120      2006-10-17 2007-02-14  0          16.99205 0.02       8.533557
16 109      2006-10-28 2007-02-14  0          34.00629 0.02      12.127444
17 120      2006-10-31 2007-02-28  0         177.12478 0.02     300.630991
18  68      2006-12-22 2007-02-28  0          66.76643 0.02      32.035059
19  96      2006-12-03 2007-03-09  0         604.44000 0.03     620.250000
20  96      2006-12-20 2007-03-26  0          13.47759 0.02      20.886600
21  86      2007-01-01 2007-03-28  0         103.18960 0.02      57.469694
22  81      2007-01-12 2007-04-03  0         111.78604 0.02     139.218723
23  83      2007-01-11 2007-04-04  0         348.24339 0.02     196.172700
24  85      2007-01-09 2007-04-04  0         689.71690 0.02     179.746568
25 113      2006-12-21 2007-04-13  0          33.28060 0.02      42.432327
26  74      2007-02-24 2007-05-09  0          32.41000 0.02      10.520000
27  65      2007-03-26 2007-05-30  0         130.22768 0.10     140.700000
28  97      2007-02-24 2007-06-01  0          49.49171 0.02      24.096654
29 113      2007-02-08 2007-06-01  0          39.83713 0.02      21.090811
30 103      2007-02-28 2007-06-11  0         119.87308 0.02      53.919211
31 115      2007-02-18 2007-06-13  0          99.43885 0.02     152.124246
32 107      2007-02-26 2007-06-13  0         134.42983 0.02     115.940000
33  92      2015-12-06 2016-03-07  0          83.87000 0.03     144.440000
34 107      2015-12-01 2016-03-17  0          82.99000 0.02     165.200000
35  95      2015-12-20 2016-03-24  0          19.32000 0.02      20.360000
36  64      2016-02-14 2016-04-18  0          68.76000 0.02      13.410000
37  82      2016-03-30 2016-06-20  0         108.15000 0.02     121.720000
38 109      2016-03-03 2016-06-20  0         175.94000 0.02      95.850000
39  74      2016-04-16 2016-06-29  0          74.34000 0.02      41.960000
40 113      2016-03-08 2016-06-29  0          81.07000 0.02      59.810000
41  94      2016-04-01 2016-07-04  0          88.39000 0.02      36.640000
42 119      2016-03-07 2016-07-04  0          11.80000 0.02       9.540000
43  97      2016-03-29 2016-07-04  0          52.79000 0.02      85.000000
44  61      2016-05-06 2016-07-06  0          16.10000 0.02      22.450000
45 116      2016-03-12 2016-07-06  0         192.51000 0.02     240.580000
46  76      2016-06-15 2016-08-30  0          95.57000 0.02      35.630000
47  68      2016-06-23 2016-08-30  0          95.14000 0.02      83.510000
48  85      2016-06-07 2016-08-31  0          51.89000 0.02      20.610000
49 102      2016-05-26 2016-09-05  0          76.31000 0.02     102.410000
50  81      2016-06-16 2016-09-05  0          80.21000 0.02      88.790000
   IgA_PostF IgG_Ga     IgA_Ga <U+22EF>        visitnursery_child visitnursery_house
1  0.02       3.7500000 0.02   <U+22EF> 0                  0
2  0.02       1.1800000 0.01   <U+22EF> 0                  1
3  1.56       4.8572239 0.07   <U+22EF> 0                  0
4  0.04       1.5491327 0.02   <U+22EF> 0                  1
5  0.02       0.9700000 0.02   <U+22EF> 0                  1
6  0.03       1.9393241 0.02   <U+22EF> 0                  0
7  0.03       1.3308644 0.02   <U+22EF> 0                  0
8  0.05       2.7600000 0.02   <U+22EF> 0                  0
9  0.02       0.1100000 0.02   <U+22EF> 0                  0
10 0.06       0.4000000 0.02   <U+22EF> 0                  0
11 9.44      10.8407933 1.00   <U+22EF> 0                  0
12 0.02       2.2311823 0.02   <U+22EF> 0                  1
13 0.05       0.5860870 0.02   <U+22EF> 0                  1
14 0.03       1.0083650 0.04   <U+22EF> 0                  0
15 0.09       0.6500000 0.02   <U+22EF> 0                  0
16 0.03       0.5100000 0.02   <U+22EF> 0                  0
17 0.02       2.2208323 0.02   <U+22EF> 0                  0
18 0.04       0.6489992 0.02   <U+22EF> 0                  0
19 0.10       2.0700000 0.02   <U+22EF> 0                  0
20 0.43       0.2700000 0.01   <U+22EF> 0                  0
21 0.02       1.7003529 0.03   <U+22EF> 0                  0
22 0.02       1.1313567 0.07   <U+22EF> 0                  1
23 0.02       2.1043327 0.02   <U+22EF> 0                  1
24 0.05       4.7080958 0.02   <U+22EF> 0                  1
25 0.01       1.0571585 0.01   <U+22EF> 0                  0
26 0.02       0.2300000 0.02   <U+22EF> 0                  0
27 0.07       3.2000000 0.02   <U+22EF> 0                  1
28 0.02       1.4479986 0.02   <U+22EF> 0                  0
29 0.06       0.8378544 0.02   <U+22EF> 0                  1
30 0.02       3.7482482 0.02   <U+22EF> 0                  0
31 0.07       2.2214860 0.02   <U+22EF> 0                  0
32 0.05       0.4100000 0.02   <U+22EF> 0                  0
33 0.02       0.6900000 0.02   <U+22EF> 0                  0
34 0.03       1.1400000 0.02   <U+22EF> 0                  0
35 0.02       0.4000000 0.02   <U+22EF> 0                  0
36 0.02       0.5600000 0.02   <U+22EF> 0                  0
37 0.02       1.2500000 0.02   <U+22EF> 0                  1
38 0.03       7.6100000 0.02   <U+22EF> 0                  1
39 0.02       6.5500000 0.02   <U+22EF> 0                  1
40 0.02       1.8600000 0.02   <U+22EF> 0                  0
41 0.02       9.8000000 0.02   <U+22EF> 0                  0
42 0.05       0.4700000 0.02   <U+22EF> 0                  1
43 0.02       0.1800000 0.02   <U+22EF> 0                  0
44 0.02       0.5800000 0.02   <U+22EF> 0                  0
45 0.02       8.6700000 0.02   <U+22EF> 0                  1
46 0.02       1.3100000 0.02   <U+22EF> 0                  0
47 0.07       3.1700000 0.02   <U+22EF> 0                  0
48 0.02       1.3800000 0.02   <U+22EF> 0                  0
49 0.02       4.2400000 0.02   <U+22EF> 0                  1
50 0.07       0.2400000 0.02   <U+22EF> 0                  0
   pregnancytime contacttotal contact04 contact59 sex Birth_mo season_birth
1  NA            NA           NA        NA        1    1       Winter
2  NA             5            1         0        2    1       Winter
3  NA            NA           NA        NA        1    3       Spring
4  NA            NA           NA        NA        1    6       Summer
5  NA             4            1         0        2    6       Summer
6  NA            NA           NA        NA        1    7       Summer
7  NA            NA           NA        NA        1    6       Summer
8  NA            NA           NA        NA        2    8       Summer
9  NA            12            3         2        1    6       Summer
10 NA             5            0         0        2    6       Summer
11 NA            NA           NA        NA        2    7       Summer
12 NA            NA           NA        NA        1   10       Autumn
13 NA            NA           NA        NA        1   10       Autumn
14 NA            NA           NA        NA        2   11       Autumn
15 NA            NA           NA        NA        2   10       Autumn
16 NA            NA           NA        NA        1   10       Autumn
17 NA            NA           NA        NA        1   10       Autumn
18 NA             0            0         0        1   12       Winter
19 NA             1            0         0        1   12       Winter
20 NA            NA           NA        NA        1   12       Winter
21 NA             0            0         0        2    1       Winter
22 NA             6            1         0        1    1       Winter
23 NA             5            2         0        2    1       Winter
24 NA             4            2         0        1    1       Winter
25 NA             3            0         0        1   12       Winter
26 NA            NA           NA        NA        2    2       Winter
27 NA            NA           NA        NA        1    3       Spring
28 NA            NA           NA        NA        2    2       Winter
29 NA             4            0         0        1    2       Winter
30 NA             1            0         0        2    2       Winter
31 NA            NA           NA        NA        2    2       Winter
32 NA            NA           NA        NA        1    2       Winter
33 39             2            0         0        1   12       Winter
34 40             1           NA        NA        1   12       Winter
35 40             2            0         0        2   12       Winter
36 37             4            1         0        2    2       Winter
37 39             0           NA        NA        2    3       Spring
38 39             4           NA        NA        1    3       Spring
39 39             6            1         0        2    4       Spring
40 40             5            2         0        1    3       Spring
41 41            38           NA        NA        2    4       Spring
42 39            71           27         7        1    3       Spring
43 39             4            0         0        1    3       Spring
44 33             0           NA        NA        2    5       Spring
45 NA             0            0         0        1    3       Spring
46 39             1            0         0        2    6       Summer
47 41             0           NA        NA        1    6       Summer
48 39             0            0         0        2    6       Summer
49 39             0            0         0        2    5       Spring
50 38             4            0         0        1    6       Summer
   agegrp
1  [60.5,121)
2  [60.5,121)
3  [60.5,121)
4  [60.5,121)
5  [60.5,121)
6  [60.5,121)
7  [60.5,121)
8  [60.5,121)
9  [60.5,121)
10 [60.5,121)
11 [60.5,121)
12 [60.5,121)
13 [60.5,121)
14 [60.5,121)
15 [60.5,121)
16 [60.5,121)
17 [60.5,121)
18 [60.5,121)
19 [60.5,121)
20 [60.5,121)
21 [60.5,121)
22 [60.5,121)
23 [60.5,121)
24 [60.5,121)
25 [60.5,121)
26 [60.5,121)
27 [60.5,121)
28 [60.5,121)
29 [60.5,121)
30 [60.5,121)
31 [60.5,121)
32 [60.5,121)
33 [60.5,121)
34 [60.5,121)
35 [60.5,121)
36 [60.5,121)
37 [60.5,121)
38 [60.5,121)
39 [60.5,121)
40 [60.5,121)
41 [60.5,121)
42 [60.5,121)
43 [60.5,121)
44 [60.5,121)
45 [60.5,121)
46 [60.5,121)
47 [60.5,121)
48 [60.5,121)
49 [60.5,121)
50 [60.5,121)

In [145]:
three <- rbind(one, two)
#head(three)

In [146]:
car.data = table(three$visitnursery_child, three$infection) 
print(car.data)

# Perform the Chi-Square test.
print(chisq.test(car.data))

    1
  0 5
  1 1

Warning message in chisq.test(car.data):
"Chi-squared approximation may be incorrect"

	Chi-squared test for given probabilities

data:  car.data
X-squared = 2.6667, df = 1, p-value = 0.1025